install.packages("shiny")
install.packages("dplyr")
install.packages("tydir")
install.packages("shinydashboard")
install.packages("caret")
install.packages("e1071")
install.packages("rpart")
install.packages("randomForest")
install.packages("plotly")
install.packages("ggplot2")

# do we need?
install.packages("ggdendro")
install.packages("factoextra")
install.packages("ggformula")
install.packages("ggeasy")